export const ErrorCodes = {
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',

  // Auth
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // DKP / Auctions
  INSUFFICIENT_DKP: 'INSUFFICIENT_DKP',
  AUCTION_CLOSED: 'AUCTION_CLOSED',
  BID_TOO_LOW: 'BID_TOO_LOW',
  SELF_BID: 'SELF_BID',

  // Calendar
  SIGNUP_LOCKED: 'SIGNUP_LOCKED',
};
